var Bypass=function(){};Bypass.on=function(){$("#bypass").addClass("fg-green");$("."+Tabs.current()).addClass("disabled");$(".bypassGrp").addClass("hidden")};Bypass.off=function(){$("#bypass").removeClass("fg-green")};Bypass.toggle=function(){Methods.save(Tabs.current()+"Bypass",!$("#bypass").hasClass("fg-green"));Power.off()};Bypass.init=function(){"true"==returnState(Tabs.current()+"Bypass")?this.on():this.off()};var Mono=function(){};Mono.on=function(){$("#monoBtn").addClass("fg-green").addClass("bdc-green").removeClass("disabled")};
Mono.off=function(){$("#monoBtn").removeClass("fg-green").removeClass("bdc-green").addClass("disabled")};Mono.init=function(){"true"==Methods.returnState("mono")?this.on():this.off()};Mono.toggle=function(){var a="true"!=Methods.returnState("mono");a?this.on():this.off();Methods.save("mono",a);Methods.sendRuntime({type:"mono",value:a})};var Karaoke=function(){};Karaoke.on=function(){$("#karaokeBtn").addClass("fg-green").addClass("bdc-green").removeClass("disabled")};Karaoke.off=function(){$("#karaokeBtn").removeClass("fg-green").removeClass("bdc-green").addClass("disabled")};
Karaoke.init=function(){"true"==Methods.returnState("karaoke")?this.on():this.off()};Karaoke.toggle=function(){var a="true"!=Methods.returnState("karaoke");1==a?this.on():this.off();Methods.save("karaoke",a);Methods.sendRuntime({type:"karaoke",value:a})};
var Power={init:function(a){Methods.sendRuntime({type:"bgInitOn",title:a})},toggle:function(){"false"==Methods.returnState("power")?location.reload():Power.off()},visualOn:function(a){$("#power").attr("class","on");Methods.setIcon("on");Popup.setVersion();Popup.setTitle(a);Popup.hideModal();Advanced.init();Pan.init();Mono.init();Karaoke.init();Tabs.gotoSavedTab();Faders.display()},visualOff:function(){$("#power").attr("class","off");Methods.setIcon("off");Popup.showModal();Popup.channelModal(Methods.getLocalizedText("offMessage"),
Methods.getLocalizedText("offTitle"));Popup.setTitle("")},on:function(a,b){Methods.save("power","true");Methods.sendRuntime({type:"bgPowerOn",value:{tabId:a,tabTitle:b}})},off:function(){Volume.reset();Power.visualOff();$("#editInBackground").hide();$("#gotoTab").hide();Methods.save("power","false");Methods.sendRuntime({type:"closeAudio"})},powerIcon:function(a,b){if($("#modalBody")[0].innerHTML==Methods.getLocalizedText("offMessage"))Power.on(a,b);else $("#modalTitle")[0].innerHTML==Methods.getLocalizedText("activeMessage")&&
Methods.sendRuntime({type:"bgPowerIcon",value:{tabId:a,tabTitle:b}})},alreadyActive:function(a){$("#power").attr("class","on");Popup.channelModal(a,Methods.getLocalizedText("activeMessage"));Popup.showModal();$("#visualizer").css({display:"inline"});Volume.display(!0)}},Volume=function(){};Volume.display=function(a){$("#volume").prop("disabled",!a)};Volume.reset=function(){Methods.sendRuntime({type:"volume",value:1});$("#volume").val(1)[0].updateBg()};var Chorus=function(){};
Chorus.show=function(){var a=$(".chorus"),b=$("#bypass");Tabs.saveAsCurrent("chorus");$("#chorusRadio").prop("checked",!0);$("#advancedLabel").addClass("hidden");$(".advanced").addClass("hidden");$("#presets").addClass("hidden");$(".module").addClass("hidden");a.removeClass("hidden");b.removeClass("hidden");$("#resetLabel").removeClass("hidden");if("true"==Methods.returnState("chorusBypass"))Bypass.on();else b.hasClass("fg-green")&&b.removeClass("fg-green"),Preset.init("chorus"),a.removeClass("disabled"),
"true"==Methods.returnState("chorusPreset")?Popup.showLoad():Popup.showSave()};Chorus.reset=function(){$("#chorusRate").val(.7)[0].updateBg();$("#chorusDepth").val(.8)[0].updateBg();$("#chorusFeedback").val(.9)[0].updateBg();$("#chorusDelay").val(1.5)[0].updateBg()};Chorus.updateNumerics=function(){$("#chorusDelayVal").html($("#chorusDelay").val());$("#chorusFeedbackVal").html($("#chorusFeedback").val());$("#chorusRateVal").html($("#chorusRate").val());$("#chorusDepthVal").html($("#chorusDepth").val())};
var Convolver=function(){};
Convolver.show=function(){var a=$(".convolver"),b=$("#bypass");Tabs.saveAsCurrent("convolver");$("#convolverRadio").prop("checked",!0);$("#advancedLabel").addClass("hidden");$(".advanced").addClass("hidden");$("#presets").addClass("hidden");$(".module").addClass("hidden");a.removeClass("hidden");b.removeClass("hidden");$("#resetLabel").removeClass("hidden");if("true"==Methods.returnState("convolverBypass"))Bypass.on();else b.hasClass("fg-green")&&b.removeClass("fg-green"),Preset.init("convolver"),
a.removeClass("disabled"),"true"==Methods.returnState("convolverPreset")?Popup.showLoad():Popup.showSave()};Convolver.reset=function(){$("#convolverWetLevel").val(0)[0].updateBg();$("#convolverDryLevel").val(1)[0].updateBg();$("#convolverHighCut").val(22050)[0].updateBg();$("#convolverLowCut").val(20)[0].updateBg()};
Convolver.updateNumerics=function(){$("#convolverDryLevelVal").html($("#convolverDryLevel").val());$("#convolverHighCutVal").html($("#convolverHighCut").val());$("#convolverLowCutVal").html($("#convolverLowCut").val());$("#convolverWetLevelVal").html($("#convolverWetLevel").val())};var Pitch=function(){};
Pitch.show=function(){var a=$(".pitch"),b=$("#bypass");Tabs.saveAsCurrent("pitch");$("#advancedLabel").addClass("hidden");$(".advanced").addClass("hidden");$("#presets").addClass("hidden");$(".chorus").addClass("hidden");$(".convolver").addClass("hidden");$(".dynamics").addClass("hidden");$(".eq").addClass("hidden");a.removeClass("hidden");b.removeClass("hidden");$("#resetLabel").removeClass("hidden");if("true"==Methods.returnState("pitchBypass"))Bypass.on();else b.hasClass("fg-green")&&b.removeClass("fg-green"),
Preset.init("pitch"),a.removeClass("disabled"),"true"==Methods.returnState("pitchPreset")?Popup.showLoad():Popup.showSave()};Pitch.reset=function(){$("#pitch").val(0)[0].updateBg();$("#pitchCents").val(0)[0].updateBg()};Pitch.updateNumerics=function(){$("#pitchVal").html($("#pitch").val());$("#pitchCentsVal").html($("#pitchCents").val())};var Equalizer=function(){};
Equalizer.show=function(){Tabs.saveAsCurrent("eq");$("#eqRadio").prop("checked",!0);$(".module").addClass("hidden");$(".advanced").addClass("hidden");$("#advancedLabel").addClass("hidden");$("#bypass").addClass("hidden");$("#resetLabel").removeClass("hidden");$("#presets").removeClass("hidden");$(".eq").removeClass("hidden");Preset.init("eq")};
Equalizer.reset=function(){$("#twenty").val(0)[0].updateBg();$("#fifty").val(0)[0].updateBg();$("#oneHundred").val(0)[0].updateBg();$("#twoHundred").val(0)[0].updateBg();$("#fiveHundred").val(0)[0].updateBg();$("#oneThousand").val(0)[0].updateBg();$("#twoThousand").val(0)[0].updateBg();$("#fiveThousand").val(0)[0].updateBg();$("#tenThousand").val(0)[0].updateBg();$("#twentyThousand").val(0)[0].updateBg()};var Limiter=function(){};
Limiter.show=function(){Tabs.saveAsCurrent("limiter");$("#limiterRadio").prop("checked",!0);$(".module").addClass("hidden");$("#presets").addClass("hidden");$("#bypass").addClass("hidden");$("#advancedLabel").removeClass("hidden");$("#resetLabel").removeClass("hidden");$(".dynamics").removeClass("hidden");$(".advanced").removeClass("hidden");Preset.init("limiter")};
Limiter.reset=function(){$("#threshold").val(0)[0].updateBg();$("#ratio").val(4)[0].updateBg();$("#knee").val(10)[0].updateBg();$("#volume").val(1)[0].updateBg();$("#release").val(.2)[0].updateBg();$("#attack").val(0)[0].updateBg()};Limiter.updateNumerics=function(){$("#thresholdVal").html($("#threshold").val());$("#attackVal").html($("#attack").val());$("#releaseVal").html($("#release").val());$("#kneeVal").html($("#knee").val());$("#ratioVal").html($("#ratio").val())};var Faders=function(){};
Faders.display=function(){$(".fadersGrp").css("opacity",1)};var Tabs=function(){};Tabs.gotoSavedTab=function(){switch(Tabs.current()){case "eq":Equalizer.show();break;case "chorus":Chorus.show();break;case "limiter":Limiter.show();break;case "convolver":Convolver.show();break;case "pitch":Pitch.show()}};Tabs.current=function(){return Methods.load("currentTab")};Tabs.saveAsCurrent=function(a){Methods.save("currentTab",a)};var Theme=function(){};
Theme.loadSelected=function(){"true"!=Methods.load("lightTheme")?Theme.makeDark("#mainPanel"):Theme.makeLight("#mainPanel")};Theme.makeLight=function(a){a=$(a);a.removeClass("inverse-all bg-base-l");a.find(".fader").removeClass("fader-inverse");a.find("button").removeClass("btn-tp");a.find("select").removeClass("select-tp");Methods.save("lightTheme","true")};
Theme.makeDark=function(a){$("#modalTitle").css({color:"#2196f3"});Methods.save("lightTheme","false");a=$(a);$("#powerIcon").css({color:"white","background-color":"#37474f",opacity:"0.5"});a.addClass("inverse-all bg-base-l");a.find(".fader").addClass("fader-inverse");a.find("button").addClass("btn-tp");a.find("select").addClass("select-tp")};var Advanced=function(){};
Advanced.init=function(){var a=$("#thresholdLabel");"true"==Methods.returnState("advanced")?(a.html(Methods.getLocalizedText("thresholdLabel")),$("#advancedLabel").addClass("fg-green"),$(".advanced").removeClass("disabled")):a.html(Methods.getLocalizedText("dynamicsLabel"))};Advanced.on=function(){var a=$("#thresholdLabel");a.html(Methods.getLocalizedText("thresholdLabel"));a.html(Methods.get);$(".advanced").removeClass("disabled");Methods.save("advanced","true");$("#advancedLabel").addClass("fg-green")};
Advanced.off=function(){Methods.save("advanced","false");$("#thresholdLabel").html(Methods.getLocalizedText("dynamicsLabel"));$("#advancedLabel").removeClass("fg-green");$(".advanced").addClass("disabled")};Advanced.toggle=function(){$(".advanced").hasClass("disabled")?this.on():this.off()};var Pan=function(){};
Pan.init=function(){$("#panFader").knob({fgColor:"#4caf50",angleOffset:-125,angleArc:250,min:-1,max:1,thickness:".3",value:Methods.load("pan"),step:.01,width:"35",height:"35",change:function(a){Methods.sendRuntime({type:"pan",value:a.toFixed(2)})},release:function(a){Methods.save("pan",a)}});this.change(Methods.load("pan"))};Pan.change=function(a){$("#panFader").val(a).trigger("change");Methods.sendRuntime({type:"pan",value:a})};
var analyserModule=function(a){function b(){drawVisual=requestAnimationFrame(b);e.getByteTimeDomainData(l);d.fillStyle=h.bg;d.fillRect(0,0,400,300);d.lineWidth=1;d.strokeStyle=h.fg;d.beginPath();for(var g=400/m,f=0,k=0;k<m;k++){var q=l[k]/128*150/2;0===k?d.moveTo(f,q):d.lineTo(f,q);f+=g}d.lineTo(n.width,n.height);d.stroke()}var c=a.stream;a=a.ctx;var h=function(){var g={},f=$("#visualizer");g.fg=f.css("color");g.bg=f.css("background-color");return g}(),p=a.createGain(),e=a.createAnalyser(),n=document.querySelector("#visualizer"),
d=n.getContext("2d");c=a.createMediaStreamSource(c);p.gain.setValueAtTime(0,a.currentTime);c.connect(e);e.connect(p);p.connect(a.destination);e.fftSize=1024;var m=e.frequencyBinCount,l=new Uint8Array(m);e.getByteTimeDomainData(l);b()},Preset={init:function(a){switch(a){case "eq":chrome.storage.sync.get("eqPreset",function(b){""!=b.eqPreset&&"undefined"!=typeof b.eqPreset?(Popup.showLoad(),b="true"):(b="false",Popup.showSave());Methods.save("eqPreset",b)});break;case "limiter":chrome.storage.sync.get("limiterPreset",
function(b){""!=b.limiterPreset&&"undefined"!=typeof b.limiterPreset?(b="true",Popup.showLoad()):(b="false",Popup.showSave());Methods.save("limiterPreset",b)});break;case "chorus":chrome.storage.sync.get("chorusPreset",function(b){""!=b.chorusPreset&&"undefined"!=typeof b.chorusPreset?(b="true",Popup.showLoad()):(b="false",Popup.showSave());Methods.save("chorusPreset",b)});break;case "convolver":chrome.storage.sync.get("convolverPreset",function(b){""!=b.convolverPreset&&"undefined"!=typeof b.convolverPreset?
(b="true",Popup.showLoad()):(b="false",Popup.showSave());Methods.save("convolverPreset",b)});break;case "pitch":chrome.storage.sync.get("pitchPreset",function(b){""!=b.pitchPreset&&"undefined"!=typeof b.pitchPreset?(b="true",Popup.showLoad()):(b="false",Popup.showSave());Methods.save("pitchPreset",b)})}},loadPreset:function(a){if("true"==Methods.returnState("volumePreset")){var b=$("#volume");b.val(Methods.load("volumePresetVal"))[0].updateBg();Methods.sendRuntime({type:"volume",value:b.val()})}switch(a){case "limiterPreset":chrome.storage.sync.get("limiterPreset",
function(c){$("#threshold").val(c.limiterPreset.threshold)[0].updateBg();$("#ratio").val(c.limiterPreset.ratio)[0].updateBg();$("#knee").val(c.limiterPreset.knee)[0].updateBg();$("#attack").val(c.limiterPreset.attack)[0].updateBg();$("#release").val(c.limiterPreset.release)[0].updateBg();Limiter.updateNumerics();Popup.sendLimiter()});break;case "eqPreset":chrome.storage.sync.get("eqPreset",function(c){$("#twenty").val(c.eqPreset.twenty)[0].updateBg();$("#fifty").val(c.eqPreset.fifty)[0].updateBg();
$("#oneHundred").val(c.eqPreset.oneHundred)[0].updateBg();$("#twoHundred").val(c.eqPreset.twoHundred)[0].updateBg();$("#fiveHundred").val(c.eqPreset.fiveHundred)[0].updateBg();$("#oneThousand").val(c.eqPreset.oneThousand)[0].updateBg();$("#twoThousand").val(c.eqPreset.twoThousand)[0].updateBg();$("#fiveThousand").val(c.eqPreset.fiveThousand)[0].updateBg();$("#tenThousand").val(c.eqPreset.tenThousand)[0].updateBg();$("#twentyThousand").val(c.eqPreset.twentyThousand)[0].updateBg();Popup.sendEq()});
break;case "chorusPreset":chrome.storage.sync.get("chorusPreset",function(c){$("#chorusRate").val(c.chorusPreset.rate)[0].updateBg();$("#chorusDepth").val(c.chorusPreset.depth)[0].updateBg();$("#chorusFeedback").val(c.chorusPreset.feedback)[0].updateBg();$("#chorusDelay").val(c.chorusPreset.delay)[0].updateBg();Chorus.updateNumerics();Popup.sendChorus()});break;case "convolverPreset":chrome.storage.sync.get("convolverPreset",function(c){$("#convolverWetLevel").val(c.convolverPreset.wetLevel)[0].updateBg();
$("#convolverDryLevel").val(c.convolverPreset.dryLevel)[0].updateBg();$("#convolverHighCut").val(c.convolverPreset.highCut)[0].updateBg();$("#convolverLowCut").val(c.convolverPreset.lowCut)[0].updateBg();Convolver.updateNumerics();Popup.sendConvolver()});break;case "pitchPreset":chrome.storage.sync.get("pitchPreset",function(c){var h=c.pitchPreset.value;c=c.pitchPreset.cents;$("#pitch").val(h)[0].updateBg();$("#pitchCents").val(c)[0].updateBg();Pitch.updateNumerics();Popup.sendPitch()})}},savePreset:function(a){"true"==
Methods.returnState("volumePreset")&&Methods.save("volumePresetVal",$("#volume").val());switch(a){case "limiterPreset":Methods.save("limiterPreset","true");chrome.storage.sync.set({limiterPreset:{threshold:$("#threshold").val(),ratio:$("#ratio").val(),knee:$("#knee").val(),attack:$("#attack").val(),release:$("#release").val()}});break;case "eqPreset":Methods.save("eqPreset","true");chrome.storage.sync.set({eqPreset:{twenty:$("#twenty").val(),fifty:$("#fifty").val(),oneHundred:$("#oneHundred").val(),
twoHundred:$("#twoHundred").val(),fiveHundred:$("#fiveHundred").val(),oneThousand:$("#oneThousand").val(),twoThousand:$("#twoThousand").val(),fiveThousand:$("#fiveThousand").val(),tenThousand:$("#tenThousand").val(),twentyThousand:$("#twentyThousand").val()}});break;case "chorusPreset":Methods.save("chorusPreset","true");chrome.storage.sync.set({chorusPreset:{rate:$("#chorusRate").val(),depth:$("#chorusDepth").val(),feedback:$("#chorusFeedback").val(),delay:$("#chorusDelay").val()}});break;case "convolverPreset":Methods.save("convolverPreset",
"true");chrome.storage.sync.set({convolverPreset:{wetLevel:$("#convolverWetLevel").val(),dryLevel:$("#convolverDryLevel").val(),highCut:$("#convolverHighCut").val(),lowCut:$("#convolverLowCut").val()}});break;case "pitchPreset":Methods.save("pitchPreset","true");a=$("#pitch").val();var b=$("#pitchCents").val();chrome.storage.sync.set({pitchPreset:{value:a,cents:b}})}},deletePreset:function(a){switch(a){case "limiter":Methods.save("limiterPreset","false");chrome.storage.sync.set({limiterPreset:""});
break;case "eq":Methods.save("eqPreset","false");chrome.storage.sync.set({eqPreset:""});break;case "chorus":Methods.save("chorusPreset","false");chrome.storage.sync.set({chorusPreset:""});break;case "convolver":Methods.save("convolverPreset","false");chrome.storage.sync.set({convolverPreset:""});break;case "pitch":Methods.save("pitchPreset","false"),chrome.storage.sync.set({pitchPreset:""})}},presetsChangeHandler:function(a){var b={acoustic:[15,15,10,4,7,7,10,12,10,5],bassBooster:[15,12,10,7,3,0,
0,0,0,0],bassReducer:[-15,-12,-10,-8,-5,0,0,7,10,12],classical:[15,12,10,8,-5,-5,0,7,10,12],dance:[12,22,15,0,5,10,16,15,12,0],deep:[15,12,5,3,10,8,5,-6,-12,-15],electronic:[14,13,4,0,-6,6,3,4,13,15],hiphop:[16,14,4,10,-4,-3,4,-2,6,10],jazz:[13,10,4,6,-5,-5,0,4,10,13],latin:[9,5,0,0,-5,-5,-5,0,10,15],loudness:[20,14,0,0,-6,0,-2,-18,16,3],lounge:[-10,-5,-2,4,13,4,0,-5,6,3],piano:[10,6,0,9,10,5,11,15,10,11],pop:[-5,-4,0,6,15,13,6,0,-3,-5],rnb:[9,23,19,4,-8,-5,8,9,10,12],rock:[16,13,10,4,-1,-2,1,8,11,
15],smallSpeakers:[18,14,13,8,4,0,-4,-9,-11,-14],spokenWord:[-7,-1,0,2,12,15,16,14,8,0],trebleBooster:[0,0,0,0,0,3,8,12,14,17],trebleReducer:[0,0,0,0,0,-3,-8,-12,-14,-17],vocalBooster:[-5,-10,-10,4,12,12,10,5,0,-5]};void 0!=b[a]&&(a=b[a],$("#twenty").val(a[0])[0].updateBg(),$("#fifty").val(a[1])[0].updateBg(),$("#oneHundred").val(a[2])[0].updateBg(),$("#twoHundred").val(a[3])[0].updateBg(),$("#fiveHundred").val(a[4])[0].updateBg(),$("#oneThousand").val(a[5])[0].updateBg(),$("#twoThousand").val(a[6])[0].updateBg(),
$("#fiveThousand").val(a[7])[0].updateBg(),$("#tenThousand").val(a[8])[0].updateBg(),$("#twentyThousand").val(a[9])[0].updateBg());Popup.sendEq()}};
