var capturedTabObj={},bgMethods=function(){};bgMethods.sendRuntime=function(a){chrome.runtime.sendMessage(a)};bgMethods.getPopup=function(){return chrome.extension.getViews({type:"popup"})[0]};bgMethods.sendAnalyserStream=function(){var a=capturedTabObj.audioCtx,b=capturedTabObj.audioCtx.createMediaStreamDestination();capturedTabObj.analyserGain.connect(b);bgMethods.getPopup().analyserModule({stream:b.stream,ctx:a})};
bgMethods.sendCaptureInterval=function(){setInterval(function(){Methods.sendRuntime({type:"Capturing Audio"})},2E3)};bgMethods.onTabRemoveListener=function(){chrome.tabs.onRemoved.addListener(function(a){a==capturedTabObj.id&&(Methods.setIcon("off"),Methods.save("power","false"),bgMethods.closeAudio(),location.reload())})};
bgMethods.sendSettings=function(a){var b={};({limiter:function(){b={type:"limiterSettings",threshold:capturedTabObj.compressor.threshold.value,attack:capturedTabObj.compressor.attack.value,release:capturedTabObj.compressor.release.value,ratio:capturedTabObj.compressor.ratio.value,knee:capturedTabObj.compressor.knee.value}},eq:function(){b={type:"eqSettings",twenty:capturedTabObj.twenty.gain.value,fifty:capturedTabObj.fifty.gain.value,oneHundred:capturedTabObj.oneHundred.gain.value,twoHundred:capturedTabObj.twoHundred.gain.value,
fiveHundred:capturedTabObj.fiveHundred.gain.value,oneThousand:capturedTabObj.oneThousand.gain.value,twoThousand:capturedTabObj.twoThousand.gain.value,fiveThousand:capturedTabObj.fiveThousand.gain.value,tenThousand:capturedTabObj.tenThousand.gain.value,twentyThousand:capturedTabObj.twentyThousand.gain.value}},chorus:function(){b={type:"chorusSettings",rate:capturedTabObj.chorus.rate,depth:capturedTabObj.chorus.depth,feedback:capturedTabObj.chorus.feedback,delay:capturedTabObj.chorusFixedDelay||1.5}},
convolver:function(){b={type:"convolverSettings",highCut:capturedTabObj.convolver.highCut,lowCut:capturedTabObj.convolver.lowCut,dryLevel:capturedTabObj.convolver.dryLevel,wetLevel:capturedTabObj.convolver.wetLevel}},volume:function(){b={type:"volumeSetting",value:capturedTabObj.volumeGainNode.gain.value}},pitch:function(){b={type:"pitchSettings",pitch:capturedTabObj.pitch.value,cents:capturedTabObj.pitch.cents}}})[a]();Methods.sendRuntime(b)};bgMethods.sendVolumeSetting=function(){bgMethods.sendSettings("volume")};
bgMethods.sendLimiterSettings=function(){bgMethods.sendSettings("limiter")};bgMethods.sendChorusSettings=function(){"true"!=Methods.returnState("chorusBypass")&&bgMethods.sendSettings("chorus")};bgMethods.sendConvolverSettings=function(){"true"!=Methods.returnState("convolverBypass")&&bgMethods.sendSettings("convolver")};bgMethods.sendPitchSettings=function(){"true"!=Methods.returnState("pitchBypass")&&bgMethods.sendSettings("pitch")};bgMethods.sendEqSettings=function(){bgMethods.sendSettings("eq")};
bgMethods.checkStream=function(){return capturedTabObj.stream?!0:!1};bgMethods.closeAudio=function(){bgMethods.checkStream()&&(capturedTabObj.stream.getAudioTracks()[0].stop(),capturedTabObj.audioCtx.close(),capturedTabObj={})};
bgMethods.createAudio=function(a){capturedTabObj.stream=a;capturedTabObj.audioCtx=new AudioContext;a=new Tuna(capturedTabObj.audioCtx);"true"!=Methods.returnState("chorusBypass")&&(capturedTabObj.chorus=new a.Chorus);"true"!=Methods.returnState("convolverBypass")&&(capturedTabObj.convolver=new a.Convolver);"true"!=Methods.returnState("pitchBypass")&&(capturedTabObj.pitch=new Jungle(capturedTabObj.audioCtx));capturedTabObj.streamOutput=capturedTabObj.audioCtx.createMediaStreamSource(capturedTabObj.stream);
capturedTabObj.analyserGain=capturedTabObj.audioCtx.createGain();capturedTabObj.panSplitter=capturedTabObj.audioCtx.createChannelSplitter(2);capturedTabObj.leftPanGain=capturedTabObj.audioCtx.createGain();capturedTabObj.rightPanGain=capturedTabObj.audioCtx.createGain();capturedTabObj.panMerger=capturedTabObj.audioCtx.createChannelMerger(2);capturedTabObj.monoSplitter=capturedTabObj.audioCtx.createChannelSplitter(2);capturedTabObj.monoGain=capturedTabObj.audioCtx.createGain();capturedTabObj.monoMerger=
capturedTabObj.audioCtx.createChannelMerger(2);capturedTabObj.volumeGainNode=capturedTabObj.audioCtx.createGain();capturedTabObj.leftKaraokeGain=capturedTabObj.audioCtx.createGain();capturedTabObj.leftKaraokeHPF=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.rightKaraokeGain=capturedTabObj.audioCtx.createGain();capturedTabObj.karaokeMerger=capturedTabObj.audioCtx.createChannelMerger(2);capturedTabObj.karaokeSplitter=capturedTabObj.audioCtx.createChannelSplitter(2);capturedTabObj.compressor=
capturedTabObj.audioCtx.createDynamicsCompressor();capturedTabObj.twenty=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.fifty=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.oneHundred=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.twoHundred=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.fiveHundred=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.oneThousand=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.twoThousand=capturedTabObj.audioCtx.createBiquadFilter();
capturedTabObj.fiveThousand=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.tenThousand=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.twentyThousand=capturedTabObj.audioCtx.createBiquadFilter();capturedTabObj.audioCtx.latencyHint="playback";capturedTabObj.twenty.type="lowshelf";capturedTabObj.twenty.frequency.setValueAtTime(32,capturedTabObj.audioCtx.currentTime);capturedTabObj.fifty.type="peaking";capturedTabObj.fifty.frequency.setValueAtTime(64,capturedTabObj.audioCtx.currentTime);
capturedTabObj.fifty.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);capturedTabObj.oneHundred.type="peaking";capturedTabObj.oneHundred.frequency.setValueAtTime(125,capturedTabObj.audioCtx.currentTime);capturedTabObj.oneHundred.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);capturedTabObj.twoHundred.type="peaking";capturedTabObj.twoHundred.frequency.setValueAtTime(250,capturedTabObj.audioCtx.currentTime);capturedTabObj.twoHundred.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);
capturedTabObj.fiveHundred.type="peaking";capturedTabObj.fiveHundred.frequency.setValueAtTime(500,capturedTabObj.audioCtx.currentTime);capturedTabObj.fiveHundred.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);capturedTabObj.oneThousand.type="peaking";capturedTabObj.oneThousand.frequency.setValueAtTime(1E3,capturedTabObj.audioCtx.currentTime);capturedTabObj.oneThousand.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);capturedTabObj.twoThousand.type="peaking";capturedTabObj.twoThousand.frequency.setValueAtTime(2E3,
capturedTabObj.audioCtx.currentTime);capturedTabObj.twoThousand.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);capturedTabObj.fiveThousand.type="peaking";capturedTabObj.fiveThousand.frequency.setValueAtTime(4E3,capturedTabObj.audioCtx.currentTime);capturedTabObj.fiveThousand.Q.setValueAtTime(5,capturedTabObj.audioCtx.currentTime);capturedTabObj.tenThousand.type="peaking";capturedTabObj.tenThousand.frequency.setValueAtTime(8E3,capturedTabObj.audioCtx.currentTime);capturedTabObj.tenThousand.Q.setValueAtTime(5,
capturedTabObj.audioCtx.currentTime);capturedTabObj.twentyThousand.type="highshelf";capturedTabObj.twentyThousand.frequency.setValueAtTime(16E3,capturedTabObj.audioCtx.currentTime);capturedTabObj.compressor.threshold.value=0;capturedTabObj.compressor.attack.value=0;capturedTabObj.compressor.release.value=.2;capturedTabObj.compressor.ratio.value=4;capturedTabObj.compressor.knee.value=10;capturedTabObj.volumeGainNode.gain.setValueAtTime(1,capturedTabObj.audioCtx.currentTime);capturedTabObj.rightKaraokeGain.gain.setValueAtTime(.5,
capturedTabObj.audioCtx.currentTime);capturedTabObj.leftKaraokeGain.gain.setValueAtTime(-.5,capturedTabObj.audioCtx.currentTime);capturedTabObj.leftKaraokeHPF.type="highpass";capturedTabObj.leftKaraokeHPF.frequency.setValueAtTime(80,capturedTabObj.audioCtx.currentTime);capturedTabObj.monoGain.gain.setValueAtTime(.5,capturedTabObj.audioCtx.currentTime);capturedTabObj.analyserGain.gain.setValueAtTime(1,capturedTabObj.audioCtx.currentTime);"true"!=Methods.returnState("pitchBypass")&&(capturedTabObj.pitch.value=
0,capturedTabObj.pitch.cents=0,capturedTabObj.pitch.setPitchOffset(0));"true"!=Methods.returnState("chorusBypass")&&(capturedTabObj.chorus.depth=.8,capturedTabObj.chorus.rate=.7,capturedTabObj.chorus.feedback=.9,capturedTabObj.chorus.delay=1.5,capturedTabObj.chorusFixedDelay=1.5,capturedTabObj.chorus.bypass=0);"true"!=Methods.returnState("convolverBypass")&&(capturedTabObj.convolver.wetLevel=0,capturedTabObj.convolver.dryLevel=1,capturedTabObj.convolver.lowCut=20,capturedTabObj.convolver.highCut=
22050,capturedTabObj.convolver.bypass=0);this.sendCaptureInterval()};
bgMethods.toggleMonoNodes=function(a){1==capturedTabObj.panMerger.context.__connectified__&&capturedTabObj.panMerger.disconnect();1==capturedTabObj.monoSplitter.context.__connectified__&&capturedTabObj.monoSplitter.disconnect();1==capturedTabObj.monoGain.context.__connectified__&&capturedTabObj.monoGain.disconnect();1==a?(capturedTabObj.panMerger.connect(capturedTabObj.monoGain),capturedTabObj.monoGain.connect(capturedTabObj.monoSplitter),capturedTabObj.monoSplitter.connect(capturedTabObj.monoMerger,
0,1),capturedTabObj.monoSplitter.connect(capturedTabObj.monoMerger,0,0),capturedTabObj.monoSplitter.connect(capturedTabObj.monoMerger,1,0)):(capturedTabObj.panMerger.connect(capturedTabObj.monoSplitter),capturedTabObj.monoSplitter.connect(capturedTabObj.monoMerger,0,0));capturedTabObj.monoSplitter.connect(capturedTabObj.monoMerger,1,1)};
bgMethods.connect=function(){capturedTabObj.streamOutput.connect(capturedTabObj.panSplitter);capturedTabObj.panSplitter.connect(capturedTabObj.leftPanGain,0);capturedTabObj.panSplitter.connect(capturedTabObj.rightPanGain,1);capturedTabObj.leftPanGain.connect(capturedTabObj.panMerger,0,0);capturedTabObj.rightPanGain.connect(capturedTabObj.panMerger,0,1);"true"==Methods.load("mono")?this.toggleMonoNodes("true"):this.toggleMonoNodes("false");"true"!=Methods.returnState("pitchBypass")&&"true"!=Methods.returnState("chorusBypass")&&
"true"!=Methods.returnState("convolverBypass")?(capturedTabObj.monoMerger.connect(capturedTabObj.pitch),capturedTabObj.pitch.output.connect(capturedTabObj.chorus),capturedTabObj.chorus.connect(capturedTabObj.convolver),capturedTabObj.convolver.connect(capturedTabObj.twenty)):"true"==Methods.returnState("pitchBypass")&&"true"!=Methods.returnState("chorusBypass")&&"true"!=Methods.returnState("convolverBypass")?(capturedTabObj.monoMerger.connect(capturedTabObj.chorus),capturedTabObj.chorus.connect(capturedTabObj.convolver),
capturedTabObj.convolver.connect(capturedTabObj.twenty)):"true"!=Methods.returnState("pitchBypass")&&Methods.returnState("chorusBypass")&&"true"!=Methods.returnState("convolverBypass")?(capturedTabObj.monoMerger.connect(capturedTabObj.pitch),capturedTabObj.pitch.output.connect(capturedTabObj.convolver),capturedTabObj.convolver.connect(capturedTabObj.twenty)):"true"!=Methods.returnState("pitchBypass")&&"true"!=Methods.returnState("chorusBypass")&&"true"==Methods.returnState("convolverBypass")?(capturedTabObj.monoMerger.connect(capturedTabObj.pitch),
capturedTabObj.pitch.output.connect(capturedTabObj.chorus),capturedTabObj.chorus.connect(capturedTabObj.twenty)):"true"!=Methods.returnState("pitchBypass")&&"true"==Methods.returnState("chorusBypass")&&"true"==Methods.returnState("convolverBypass")?(capturedTabObj.monoMerger.connect(capturedTabObj.pitch),capturedTabObj.pitch.output.connect(capturedTabObj.twenty)):"true"==Methods.returnState("pitchBypass")&&"true"==Methods.returnState("chorusBypass")&&"true"!=Methods.returnState("convolverBypass")?
(capturedTabObj.monoMerger.connect(capturedTabObj.convolver),capturedTabObj.convolver.connect(capturedTabObj.twenty)):"true"==Methods.returnState("pitchBypass")&&"true"!=Methods.returnState("chorusBypass")&&"true"==Methods.returnState("convolverBypass")?(capturedTabObj.monoMerger.connect(capturedTabObj.chorus),capturedTabObj.chorus.connect(capturedTabObj.twenty)):"true"==Methods.returnState("pitchBypass")&&"true"==Methods.returnState("chorusBypass")&&"true"==Methods.returnState("convolverBypass")&&
capturedTabObj.monoMerger.connect(capturedTabObj.twenty);capturedTabObj.twenty.connect(capturedTabObj.fifty);capturedTabObj.fifty.connect(capturedTabObj.oneHundred);capturedTabObj.oneHundred.connect(capturedTabObj.twoHundred);capturedTabObj.twoHundred.connect(capturedTabObj.fiveHundred);capturedTabObj.fiveHundred.connect(capturedTabObj.oneThousand);capturedTabObj.oneThousand.connect(capturedTabObj.twoThousand);capturedTabObj.twoThousand.connect(capturedTabObj.fiveThousand);capturedTabObj.fiveThousand.connect(capturedTabObj.tenThousand);
capturedTabObj.tenThousand.connect(capturedTabObj.twentyThousand);capturedTabObj.twentyThousand.connect(capturedTabObj.compressor);capturedTabObj.compressor.connect(capturedTabObj.volumeGainNode);"true"==Methods.load("karaoke")?this.toggleKaraoke("true"):this.toggleKaraoke("false")};
bgMethods.toggleKaraoke=function(a){1==a?(capturedTabObj.volumeGainNode.disconnect(),capturedTabObj.volumeGainNode.connect(capturedTabObj.karaokeSplitter),capturedTabObj.karaokeSplitter.connect(capturedTabObj.leftKaraokeGain,0),capturedTabObj.karaokeSplitter.connect(capturedTabObj.rightKaraokeGain,1),capturedTabObj.leftKaraokeGain.connect(capturedTabObj.leftKaraokeHPF),capturedTabObj.leftKaraokeHPF.connect(capturedTabObj.karaokeMerger,0,0),capturedTabObj.leftKaraokeGain.connect(capturedTabObj.karaokeMerger,
0,1),capturedTabObj.rightKaraokeGain.connect(capturedTabObj.karaokeMerger,0,1),capturedTabObj.rightKaraokeGain.connect(capturedTabObj.karaokeMerger,0,0),capturedTabObj.karaokeMerger.connect(capturedTabObj.analyserGain)):(capturedTabObj.volumeGainNode.disconnect(),capturedTabObj.volumeGainNode.connect(capturedTabObj.analyserGain));capturedTabObj.analyserGain.connect(capturedTabObj.audioCtx.destination)};
bgMethods.initOn=function(a){bgMethods.sendVolumeSetting();bgMethods.sendEqSettings();bgMethods.sendLimiterSettings();bgMethods.sendChorusSettings();bgMethods.sendConvolverSettings();bgMethods.sendPitchSettings();bgMethods.sendAnalyserStream();bgMethods.sendRuntime({type:"popupVisualOn",value:a})};
bgMethods.powerIcon=function(a,b){capturedTabObj.stream.getAudioTracks()[0].stop();chrome.tabCapture.capture({audio:!0,video:!1},function(c){capturedTabObj.stream=c;capturedTabObj.streamOutput=capturedTabObj.audioCtx.createMediaStreamSource(capturedTabObj.stream);capturedTabObj.streamOutput.connect(capturedTabObj.panSplitter);capturedTabObj.title=b;capturedTabObj.id=a;bgMethods.onTabRemoveListener(a);bgMethods.sendAnalyserStream();bgMethods.initOn(b)})};
bgMethods.powerOn=function(a,b){chrome.tabCapture.capture({audio:!0,video:!1},function(c){null==c?bgMethods.sendRuntime({type:"popupPowerOff"}):(capturedTabObj.id=a,capturedTabObj.title=b,bgMethods.createAudio(c),bgMethods.pan(Methods.load("pan")),bgMethods.connect(),"true"==Methods.returnState("autoLoadPreset")?("true"==Methods.returnState("limiterPreset")?bgMethods.getPopup().Preset.loadPreset("limiterPreset"):bgMethods.sendLimiterSettings(),"true"==Methods.returnState("eqPreset")?bgMethods.getPopup().Preset.loadPreset("eqPreset"):
bgMethods.sendEqSettings(),"true"==Methods.returnState("chorusPreset")?bgMethods.getPopup().Preset.loadPreset("chorusPreset"):bgMethods.sendChorusSettings(),"true"==Methods.returnState("convolverPreset")?bgMethods.getPopup().Preset.loadPreset("convolverPreset"):bgMethods.sendConvolverSettings(),"true"==Methods.returnState("pitchPreset")?bgMethods.getPopup().Preset.loadPreset("pitchPreset"):bgMethods.sendPitchSettings()):(bgMethods.sendVolumeSetting(),bgMethods.sendEqSettings(),bgMethods.sendLimiterSettings(),
bgMethods.sendChorusSettings(),bgMethods.sendConvolverSettings(),bgMethods.sendPitchSettings()));bgMethods.onTabRemoveListener(a);bgMethods.sendAnalyserStream();bgMethods.sendRuntime({type:"popupVisualOn",value:b})})};
bgMethods.fullScreen=function(a){"active"==a.status&&a.tabId==capturedTabObj.id&&chrome.windows.getCurrent(function(b){var c=b.id;"false"!=Methods.load("fullScreen")?1==a.fullscreen?(Methods.save("windowState",b.state),chrome.windows.update(c,{state:"fullscreen"},null)):chrome.windows.update(c,{state:Methods.load("windowState")},null):chrome.windows.update(c,{state:b.state},null)})};
bgMethods.pan=function(a){a=Number(a);0<a?(capturedTabObj.leftPanGain.gain.setValueAtTime(1-a,capturedTabObj.audioCtx.currentTime),capturedTabObj.rightPanGain.gain.setValueAtTime(1,capturedTabObj.audioCtx.currentTime)):(capturedTabObj.leftPanGain.gain.setValueAtTime(1,capturedTabObj.audioCtx.currentTime),capturedTabObj.rightPanGain.gain.setValueAtTime(1+a,capturedTabObj.audioCtx.currentTime))};
var Background=function(){Methods.setIcon("off");Background.install();Background.clearStorage();Background.initListener();window.onbeforeunload=Background.emptyTabObj()};
Background.initListener=function(){chrome.runtime.onMessage.addListener(function(a){var b=a.type,c=a.value;"twenty"!=b&&"fifty"!=b&&"oneHundred"!=b&&"twoHundred"!=b&&"fiveHundred"!=b&&"oneThousand"!=b&&"twoThousand"!=b&&"fiveThousand"!=b&&"tenThousand"!=b&&"twentyThousand"!=b||-20!=Number(c)||(c=-40);switch(b){case "threshold":capturedTabObj.compressor.threshold.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "attack":capturedTabObj.compressor.attack.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);
break;case "release":capturedTabObj.compressor.release.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "knee":capturedTabObj.compressor.knee.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "ratio":capturedTabObj.compressor.ratio.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "volume":capturedTabObj.volumeGainNode.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "twenty":capturedTabObj.twenty.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);
break;case "fifty":capturedTabObj.fifty.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "oneHundred":capturedTabObj.oneHundred.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "twoHundred":capturedTabObj.twoHundred.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "fiveHundred":capturedTabObj.fiveHundred.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "oneThousand":capturedTabObj.oneThousand.gain.setValueAtTime(c,
capturedTabObj.audioCtx.currentTime);break;case "twoThousand":capturedTabObj.twoThousand.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "fiveThousand":capturedTabObj.fiveThousand.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "tenThousand":capturedTabObj.tenThousand.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "twentyThousand":capturedTabObj.twentyThousand.gain.setValueAtTime(c,capturedTabObj.audioCtx.currentTime);break;case "sendAnalyserStream":bgMethods.sendAnalyserStream();
break;case "bgPowerIcon":bgMethods.powerIcon(c.tabId,c.tabTitle);break;case "bgPowerOn":bgMethods.powerOn(c.tabId,c.tabTitle);break;case "bgInitOn":bgMethods.initOn(a.title);break;case "closeAudio":bgMethods.closeAudio();location.reload();break;case "checkStream":bgMethods.checkStream();break;case "mono":bgMethods.toggleMonoNodes(c);break;case "karaoke":bgMethods.toggleKaraoke(c);break;case "sendSettingsToPopup":bgMethods.sendVolumeSetting();bgMethods.sendEqSettings();bgMethods.sendLimiterSettings();
bgMethods.sendPitchSettings();bgMethods.sendChorusSettings();bgMethods.sendConvolverSettings();bgMethods.sendRuntime("popupVisualOn");break;case "pan":bgMethods.pan(c)}"true"!=Methods.returnState("pitchBypass")&&"pitch"==b&&(capturedTabObj.pitch.value=c,capturedTabObj.pitch.setPitchOffset(Number(c)+Number(capturedTabObj.pitch.cents/100||0)));"true"!=Methods.returnState("pitchBypass")&&"pitchCents"==b&&(capturedTabObj.pitch.cents=a.value,capturedTabObj.pitch.setPitchOffset(Number(capturedTabObj.pitch.value)+
Number(a.value/100)));"true"!=Methods.returnState("convolverBypass")&&("convolverHighCut"==b&&(capturedTabObj.convolver.highCut=c),"convolverLowCut"==b&&(capturedTabObj.convolver.lowCut=c),"convolverDryLevel"==b&&(capturedTabObj.convolver.dryLevel=c),"convolverWetLevel"==b&&(capturedTabObj.convolver.wetLevel=c));"true"!=Methods.returnState("chorusBypass")&&("chorusRate"==b&&(capturedTabObj.chorus.rate=a.value),"chorusDepth"==b&&(capturedTabObj.chorus.depth=a.value),"chorusFeedback"==b&&(capturedTabObj.chorus.feedback=
a.value),"chorusDelay"==b&&(capturedTabObj.chorus.delay=a.value,capturedTabObj.chorusFixedDelay=a.value))});chrome.tabCapture.onStatusChanged.addListener(bgMethods.fullScreen)};Background.emptyTabObj=function(){capturedTabObj={}};Background.clearStorage=function(){Methods.save("instance","false");Methods.save("power","false")};
Background.install=function(){chrome.runtime.onInstalled.addListener(function(a){"install"==a.reason&&(Methods.save("mono","false"),Methods.save("karaoke","false"),Methods.save("convolverBypass","true"),Methods.save("pitchBypass","true"),Methods.save("chorusBypass","true"),Methods.save("currentTab","limiter"),Methods.save("autoOpen","false"),Methods.save("info","true"),Methods.save("volumePreset","true"),Methods.save("lightTheme","false"),Methods.save("autoLoadPreset","true"),Methods.save("fullScreen",
"true"),Methods.save("pan","0"))})};var bg=new Background;

